# Cleaning dataset: Air Quality Database

Source: WHO Air Quality Database 2023, version 6.0
Local filename: WHO_annual_mean_pm25.csv

Concentrations of fine particulate matter (PM2.5) of all countries from 2011 - 2019
Mean values and range[min, max]

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('WHO_,annual_mean_pm25.csv')
df.head()

,Unnamed: 0,Concentrations of fine particulate matter (PM2.5),Concentrations of fine particulate matter (PM2.5).1,Concentrations of fine particulate matter (PM2.5).2,Concentrations of fine particulate matter (PM2.5).3,Concentrations of fine particulate matter (PM2.5).4,Concentrations of fine particulate matter (PM2.5).5,Concentrations of fine particulate matter (PM2.5).6,Concentrations of fine particulate matter (PM2.5).7,Concentrations of fine particulate matter (PM2.5).8,...,Concentrations of fine particulate matter (PM2.5).40,Concentrations of fine particulate matter (PM2.5).41,Concentrations of fine particulate matter (PM2.5).42,Concentrations of fine particulate matter (PM2.5).43,Concentrations of fine particulate matter (PM2.5).44,Concentrations of fine particulate matter (PM2.5).45,Concentrations of fine particulate matter (PM2.5).46,Concentrations of fine particulate matter (PM2.5).47,Concentrations of fine particulate matter (PM2.5).48,Concentrations of fine particulate matter (PM2.5).49
0,NaN,2019,2019,2019,2019,2019,2018,2018,2018,2018,...,2011,2011,2011,2011,2011,2010,2010,2010,2010,2010
1,"Countries, territories and areas",Total,Urban,Rural,Cities,Towns,Total,Urban,Rural,Cities,...,Total,Urban,Rural,Cities,Towns,Total,Urban,Rural,Cities,Towns
2,Afghanistan,62.49 [45.04-86.46],75.19 [53.87-102.87],56.00 [39.42-77.13],84.04 [60.77-114.90],62.47 [44.97-86.91],70.25 [50.62-97.15],83.50 [60.10-113.39],63.50 [44.48-87.48],92.57 [67.33-126.55],...,66.94 [48.90-92.62],80.45 [57.67-110.73],60.11 [42.82-83.13],89.57 [64.75-122.95],67.72 [48.37-93.74],68.97 [49.48-96.51],83.13 [60.37-117.80],61.81 [42.68-87.77],92.79 [66.17-128.44],69.67 [48.91-98.81]
3,Albania,16.28 [14.73-18.21],16.58 [14.98-18.62],15.65 [14.01-17.67],16.70 [15.03-18.80],16.40 [14.49-18.62],19.76 [17.97-21.90],20.09 [18.27-22.30],19.07 [17.04-21.34],20.18 [18.22-22.49],...,23.00 [20.57-25.75],23.39 [21.23-25.95],22.34 [19.81-25.13],23.41 [21.01-26.05],23.38 [20.55-26.56],21.95 [19.82-24.69],22.30 [20.33-24.90],21.38 [19.01-23.96],22.24 [20.06-24.82],22.37 [19.72-25.35]
4,Algeria,22.68 [14.54-35.29],22.85 [14.51-35.46],22.38 [14.20-35.42],23.75 [14.80-36.27],21.74 [13.85-34.38],22.73 [14.57-35.30],22.84 [14.50-35.44],22.53 [14.26-35.63],23.74 [14.81-36.26],...,21.56 [14.03-33.06],21.43 [13.98-32.79],21.78 [14.00-34.19],22.08 [14.33-33.19],20.68 [13.42-32.34],21.27 [13.92-32.39],21.02 [13.83-32.06],21.72 [13.97-34.12],21.67 [14.19-32.69],20.29 [13.28-31.53]

### Make a new table with only total values

In [3]:
df_total = df
df_total = df.iloc[:, [0, 1, 6, 11, 16, 21, 26, 31, 36, 41, 46]]
df_total

,Unnamed: 0,Concentrations of fine particulate matter (PM2.5),Concentrations of fine particulate matter (PM2.5).5,Concentrations of fine particulate matter (PM2.5).10,Concentrations of fine particulate matter (PM2.5).15,Concentrations of fine particulate matter (PM2.5).20,Concentrations of fine particulate matter (PM2.5).25,Concentrations of fine particulate matter (PM2.5).30,Concentrations of fine particulate matter (PM2.5).35,Concentrations of fine particulate matter (PM2.5).40,Concentrations of fine particulate matter (PM2.5).45
0,NaN,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
1,"Countries, territories and areas",Total,Total,Total,Total,Total,Total,Total,Total,Total,Total
2,Afghanistan,62.49 [45.04-86.46],70.25 [50.62-97.15],61.78 [44.81-85.24],64.00 [46.01-87.23],67.20 [49.05-92.67],68.06 [49.36-93.43],72.18 [52.57-99.67],68.26 [49.60-94.02],66.94 [48.90-92.62],68.97 [49.48-96.51]
3,Albania,16.28 [14.73-18.21],19.76 [17.97-21.90],19.01 [17.22-21.12],18.15 [16.42-20.18],18.98 [17.17-21.23],19.13 [17.34-21.32],19.77 [17.95-22.19],21.70 [19.51-24.28],23.00 [20.57-25.75],21.95 [19.82-24.69]
4,Algeria,22.68 [14.54-35.29],22.73 [14.57-35.30],23.33 [14.84-36.41],23.06 [14.73-35.92],22.49 [14.46-34.91],22.64 [14.54-35.12],21.19 [13.87-32.32],22.76 [14.57-35.60],21.56 [14.03-33.06],21.27 [13.92-32.39]
...,...,...,...,...,...,...,...,...,...,...,...
192,Venezuela (Bolivarian Republic of),16.21 [11.55-21.76],17.06 [12.50-22.84],18.71 [13.71-25.61],19.65 [14.06-26.59],20.12 [14.42-27.06],19.84 [14.56-26.04],21.00 [15.35-28.55],19.87 [14.90-26.76],20.71 [15.08-27.27],20.67 [14.60-28.32]
193,Viet Nam,20.89 [16.58-24.31],20.09 [16.58-23.39],20.10 [16.27-23.82],22.37 [17.96-26.83],20.47 [16.11-24.56],20.08 [16.06-23.84],22.62 [18.21-26.61],21.67 [17.44-25.63],20.67 [16.31-24.56],22.37 [16.93-27.87]
194,Yemen,41.61 [14.40-85.18],41.62 [14.37-85.36],41.32 [14.26-84.71],39.91 [13.91-80.68],41.06 [14.20-84.02],38.27 [13.57-75.95],41.02 [14.21-83.75],42.49 [14.59-87.92],41.03 [14.20-83.84],38.83 [13.65-77.63]
195,Zambia,16.90 [7.65-31.61],16.99 [7.65-31.83],16.99 [7.66-31.85],17.32 [7.70-32.70],17.43 [7.75-32.99],17.29 [7.70-32.68],17.24 [7.68-32.52],17.55 [7.80-33.31],17.33 [7.71-32.70],17.09 [7.63-32.11]
196,Zimbabwe,13.08 [7.05-22.70],13.12 [7.07-22.79],13.15 [7.08-22.90],13.09 [7.05-22.78],13.27 [7.12-23.39],13.12 [7.07-22.85],13.10 [7.05-22.78],13.21 [7.09-23.25],13.27 [7.11-23.42],13.28 [7.11-23.48]

In [4]:
# Rename column names

new_columns = ['Country','2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010' ]
df_total.columns = new_columns

In [5]:
# Drop top two rows

df_total = df_total.drop(df_total.index[[0,1]])

df_total

,Country,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
2,Afghanistan,62.49 [45.04-86.46],70.25 [50.62-97.15],61.78 [44.81-85.24],64.00 [46.01-87.23],67.20 [49.05-92.67],68.06 [49.36-93.43],72.18 [52.57-99.67],68.26 [49.60-94.02],66.94 [48.90-92.62],68.97 [49.48-96.51]
3,Albania,16.28 [14.73-18.21],19.76 [17.97-21.90],19.01 [17.22-21.12],18.15 [16.42-20.18],18.98 [17.17-21.23],19.13 [17.34-21.32],19.77 [17.95-22.19],21.70 [19.51-24.28],23.00 [20.57-25.75],21.95 [19.82-24.69]
4,Algeria,22.68 [14.54-35.29],22.73 [14.57-35.30],23.33 [14.84-36.41],23.06 [14.73-35.92],22.49 [14.46-34.91],22.64 [14.54-35.12],21.19 [13.87-32.32],22.76 [14.57-35.60],21.56 [14.03-33.06],21.27 [13.92-32.39]
5,Andorra,8.52 [7.49-10.05],9.21 [8.08-10.85],9.31 [8.16-10.97],9.06 [7.93-10.71],9.94 [8.72-11.68],9.35 [8.23-11.04],10.15 [8.88-11.93],10.80 [9.44-12.71],11.66 [10.25-13.69],11.43 [10.07-13.43]
6,Angola,27.16 [5.85-89.91],25.85 [5.84-82.46],25.44 [5.89-78.84],26.08 [6.01-80.35],25.03 [6.03-73.14],24.12 [6.02-68.30],24.53 [6.11-68.88],24.01 [6.13-65.45],24.67 [6.18-67.99],24.20 [6.17-65.55]
...,...,...,...,...,...,...,...,...,...,...,...
192,Venezuela (Bolivarian Republic of),16.21 [11.55-21.76],17.06 [12.50-22.84],18.71 [13.71-25.61],19.65 [14.06-26.59],20.12 [14.42-27.06],19.84 [14.56-26.04],21.00 [15.35-28.55],19.87 [14.90-26.76],20.71 [15.08-27.27],20.67 [14.60-28.32]
193,Viet Nam,20.89 [16.58-24.31],20.09 [16.58-23.39],20.10 [16.27-23.82],22.37 [17.96-26.83],20.47 [16.11-24.56],20.08 [16.06-23.84],22.62 [18.21-26.61],21.67 [17.44-25.63],20.67 [16.31-24.56],22.37 [16.93-27.87]
194,Yemen,41.61 [14.40-85.18],41.62 [14.37-85.36],41.32 [14.26-84.71],39.91 [13.91-80.68],41.06 [14.20-84.02],38.27 [13.57-75.95],41.02 [14.21-83.75],42.49 [14.59-87.92],41.03 [14.20-83.84],38.83 [13.65-77.63]
195,Zambia,16.90 [7.65-31.61],16.99 [7.65-31.83],16.99 [7.66-31.85],17.32 [7.70-32.70],17.43 [7.75-32.99],17.29 [7.70-32.68],17.24 [7.68-32.52],17.55 [7.80-33.31],17.33 [7.71-32.70],17.09 [7.63-32.11]
196,Zimbabwe,13.08 [7.05-22.70],13.12 [7.07-22.79],13.15 [7.08-22.90],13.09 [7.05-22.78],13.27 [7.12-23.39],13.12 [7.07-22.85],13.10 [7.05-22.78],13.21 [7.09-23.25],13.27 [7.11-23.42],13.28 [7.11-23.48]

### Use values only (mean)

- remove range [min - max] for now
- can be used later

In [6]:
columns_to_process = ['2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010']

for col in columns_to_process:
    df_total[col] = df_total[col].str.extract(r'^([\d.]+)')

df_total

,Country,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
2,Afghanistan,62.49,70.25,61.78,64.00,67.20,68.06,72.18,68.26,66.94,68.97
3,Albania,16.28,19.76,19.01,18.15,18.98,19.13,19.77,21.70,23.00,21.95
4,Algeria,22.68,22.73,23.33,23.06,22.49,22.64,21.19,22.76,21.56,21.27
5,Andorra,8.52,9.21,9.31,9.06,9.94,9.35,10.15,10.80,11.66,11.43
6,Angola,27.16,25.85,25.44,26.08,25.03,24.12,24.53,24.01,24.67,24.20
...,...,...,...,...,...,...,...,...,...,...,...
192,Venezuela (Bolivarian Republic of),16.21,17.06,18.71,19.65,20.12,19.84,21.00,19.87,20.71,20.67
193,Viet Nam,20.89,20.09,20.10,22.37,20.47,20.08,22.62,21.67,20.67,22.37
194,Yemen,41.61,41.62,41.32,39.91,41.06,38.27,41.02,42.49,41.03,38.83
195,Zambia,16.90,16.99,16.99,17.32,17.43,17.29,17.24,17.55,17.33,17.09
196,Zimbabwe,13.08,13.12,13.15,13.09,13.27,13.12,13.10,13.21,13.27,13.28

In [7]:
# Exporting to clean csv
df_total.to_csv('mean_pm25.csv', index=False)

### Safe levels of pm2.5 = 10

Find countries which are above and below these safe levels

In [8]:
# Below safe levels in 2019

countries_below_10 = df_total[df_total['2019'].astype(float) < 10]

countries_below_10

,Country,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
5,Andorra,8.52,9.21,9.31,9.06,9.94,9.35,10.15,10.80,11.66,11.43
7,Antigua and Barbuda,8.30,8.87,9.27,8.95,8.89,8.50,8.05,8.20,7.79,8.17
10,Australia,8.93,7.11,6.89,6.67,6.60,6.91,7.26,7.31,8.08,9.03
13,Bahamas,5.20,5.61,5.80,5.56,5.32,5.32,5.08,5.28,4.92,4.97
16,Barbados,9.79,10.36,10.91,10.34,10.53,9.95,9.32,9.60,9.04,9.15
26,Brunei Darussalam,6.86,6.70,7.03,7.91,7.81,8.02,8.08,7.62,8.42,8.33
33,Canada,6.39,7.09,6.90,6.31,7.15,7.29,7.41,7.71,7.87,7.76
41,Cook Islands,7.80,7.76,7.60,7.62,7.45,7.36,7.44,7.43,7.30,7.46
50,Denmark,9.66,10.02,9.97,9.78,10.73,10.39,10.97,11.44,12.98,12.27
52,Dominica,8.22,8.75,9.23,8.88,8.81,8.36,7.89,8.12,7.70,7.86
53,Dominican Republic,7.59,8.00,8.32,8.02,7.87,7.70,7.22,7.46,7.04,7.52
59,Estonia,6.35,6.70,5.90,6.20,6.75,7.85,7.63,7.38,7.65,8.47
62,Fiji,7.36,7.52,7.45,7.39,7.32,7.23,7.12,7.10,7.04,7.19
63,Finland,5.47,5.57,5.37,5.39,5.83,5.77,6.20,6.33,7.03,7.07
76,Haiti,9.69,10.23,10.61,10.36,10.14,9.92,9.37,9.61,9.05,9.56
79,Iceland,5.79,5.89,5.75,5.69,6.43,6.03,6.39,6.64,7.46,6.91
84,Ireland,8.20,8.31,8.13,8.08,9.16,8.74,9.33,9.43,10.60,9.90
92,Kiribati,7.62,7.67,7.63,7.64,7.31,7.33,7.55,7.54,7.62,7.60
102,Luxembourg,8.89,9.71,9.84,9.75,10.45,10.27,11.03,11.32,12.63,12.38
109,Marshall Islands,7.21,7.14,7.15,7.27,7.10,6.97,7.21,7.12,7.07,7.27
113,Micronesia (Federated States of),7.79,7.63,7.62,7.73,7.65,7.37,7.64,7.46,7.35,7.55
114,Monaco,9.21,9.88,9.63,9.53,10.41,9.97,10.77,11.16,12.37,11.91
121,Nauru,7.40,7.59,7.45,7.33,7.28,7.18,7.37,7.40,7.58,7.50
124,New Zealand,8.61,7.45,7.14,6.91,6.94,7.19,7.51,7.67,8.54,9.35
128,Niue,6.74,6.73,6.64,6.75,6.53,6.52,6.41,6.43,6.34,6.44
129,Norway,6.30,6.33,6.36,6.33,6.82,6.62,7.13,7.33,8.32,7.86
133,Palau,7.82,7.77,7.50,7.59,8.02,7.76,7.77,7.78,7.61,7.23
135,Papua New Guinea,8.89,8.93,8.87,8.69,8.97,8.39,8.39,8.39,8.28,8.65
140,Portugal,7.34,7.90,9.04,8.42,8.68,7.90,9.44,9.43,10.68,10.55
146,Russian Federation,8.88,9.22,8.38,8.71,9.49,10.80,10.46,10.22,10.53,11.88
148,Saint Kitts and Nevis,8.05,8.59,8.97,8.66,8.59,8.22,7.75,7.91,7.53,7.93
149,Saint Lucia,8.98,9.51,10.03,9.56,9.62,9.10,8.55,8.81,8.34,8.43
150,Saint Vincent and the Grenadines,9.41,9.94,10.50,10.05,10.09,9.55,8.97,9.23,8.75,8.85
151,Samoa,7.78,7.77,7.67,7.62,7.76,7.55,7.64,7.56,7.48,7.40
152,San Marino,9.85,10.81,10.55,10.33,11.42,11.00,11.72,12.12,13.44,13.02
162,Solomon Islands,7.83,7.95,7.80,7.76,7.86,7.62,7.54,7.43,7.37,7.42
166,Spain,9.34,10.08,10.21,10.04,11.11,10.31,11.22,11.83,13.09,12.72
170,Sweden,5.96,6.09,5.93,5.88,6.37,6.30,6.61,6.90,7.76,7.52
171,Switzerland,8.97,10.01,9.89,9.99,10.82,10.51,11.38,11.74,13.00,12.76
177,Tonga,7.52,7.47,7.38,7.40,7.26,7.20,7.09,7.10,7.05,7.14
182,Tuvalu,6.81,6.94,6.85,6.70,6.95,6.78,6.81,6.87,6.95,6.76
186,United Kingdom of Great Britain and Northern I...,9.52,10.07,10.09,10.19,11.08,10.95,11.82,12.14,13.41,13.17
188,United States of America,7.18,8.13,7.96,7.54,8.31,8.62,8.75,9.07,9.36,9.29
189,Uruguay,8.48,8.82,9.27,9.75,9.90,9.52,9.72,9.03,9.20,9.18
191,Vanuatu,8.42,8.81,8.62,8.66,8.62,8.36,8.31,8.19,8.23,8.09

In [9]:
grouped_counts = df_total['2019'].astype(float).apply(lambda x: 'Above 10' if x > 10 else 'Below 10').value_counts()

grouped_counts

2019
Above 10    150
Below 10     45
Name: count, dtype: int64

In [10]:
# Use country_converter to assign a Continent to a Country as a new column 
# pip install country_converter

import country_converter as coco

cc = coco.CountryConverter()
df_total['continent'] = df_total['Country'].apply(lambda x: cc.convert(x, to='continent'))
df_total.insert(loc=1, column='Continent', value=df_total['continent'])
df_total = df_total.drop(columns=['continent'])

df_total

,Country,Continent,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
2,Afghanistan,Asia,62.49,70.25,61.78,64.00,67.20,68.06,72.18,68.26,66.94,68.97
3,Albania,Europe,16.28,19.76,19.01,18.15,18.98,19.13,19.77,21.70,23.00,21.95
4,Algeria,Africa,22.68,22.73,23.33,23.06,22.49,22.64,21.19,22.76,21.56,21.27
5,Andorra,Europe,8.52,9.21,9.31,9.06,9.94,9.35,10.15,10.80,11.66,11.43
6,Angola,Africa,27.16,25.85,25.44,26.08,25.03,24.12,24.53,24.01,24.67,24.20
...,...,...,...,...,...,...,...,...,...,...,...,...
192,Venezuela (Bolivarian Republic of),America,16.21,17.06,18.71,19.65,20.12,19.84,21.00,19.87,20.71,20.67
193,Viet Nam,Asia,20.89,20.09,20.10,22.37,20.47,20.08,22.62,21.67,20.67,22.37
194,Yemen,Asia,41.61,41.62,41.32,39.91,41.06,38.27,41.02,42.49,41.03,38.83
195,Zambia,Africa,16.90,16.99,16.99,17.32,17.43,17.29,17.24,17.55,17.33,17.09
196,Zimbabwe,Africa,13.08,13.12,13.15,13.09,13.27,13.12,13.10,13.21,13.27,13.28

In [13]:
# Check for no null values and continent assigned to all countries
df_total.notna().sum()

Country      195
Continent    195
2019         195
2018         195
2017         195
2016         195
2015         195
2014         195
2013         195
2012         195
2011         195
2010         195
dtype: int64