In [25]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# Import data
df_mean = pd.read_csv("pm25_mean.csv")  


df_mean

,Country,Continent,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistan,Asia,68.97,66.94,68.26,72.18,68.06,67.20,64.00,61.78,70.25,62.49
1,Albania,Europe,21.95,23.00,21.70,19.77,19.13,18.98,18.15,19.01,19.76,16.28
2,Algeria,Africa,21.27,21.56,22.76,21.19,22.64,22.49,23.06,23.33,22.73,22.68
3,Andorra,Europe,11.43,11.66,10.80,10.15,9.35,9.94,9.06,9.31,9.21,8.52
4,Angola,Africa,24.20,24.67,24.01,24.53,24.12,25.03,26.08,25.44,25.85,27.16
...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela (Bolivarian Republic of),America,20.67,20.71,19.87,21.00,19.84,20.12,19.65,18.71,17.06,16.21
191,Viet Nam,Asia,22.37,20.67,21.67,22.62,20.08,20.47,22.37,20.10,20.09,20.89
192,Yemen,Asia,38.83,41.03,42.49,41.02,38.27,41.06,39.91,41.32,41.62,41.61
193,Zambia,Africa,17.09,17.33,17.55,17.24,17.29,17.43,17.32,16.99,16.99,16.90
194,Zimbabwe,Africa,13.28,13.27,13.21,13.10,13.12,13.27,13.09,13.15,13.12,13.08

In [26]:
# Select all countries from 2010-2019
X = df_mean.iloc[:, 2:10]
y = df_mean.iloc[:, 11:12]


# Splitting into train and test sets
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

# Predict using Linear Regression
model_mean = LinearRegression()
model_mean.fit(x_train, y_train)

predict_2019 = model_mean.predict(x_test)

predict_2019

array([[18.36964342],
       [13.77129507],
       [15.29228188],
       [44.30810351],
       [20.92287077],
       [ 6.30507563],
       [ 5.71997653],
       [ 9.28603172],
       [17.92532375],
       [32.61266659],
       [14.85973382],
       [12.67018593],
       [10.65158057],
       [43.30061775],
       [40.13333984],
       [18.46083064],
       [40.518629  ],
       [ 7.12172199],
       [11.28127402],
       [ 8.95245788],
       [ 8.26645106],
       [21.69592888],
       [14.23649221],
       [17.50919074],
       [11.74642481],
       [18.88570503],
       [10.3115785 ],
       [12.32804461],
       [ 7.58044376],
       [36.09122955],
       [10.04883617],
       [42.87556939],
       [15.0997752 ],
       [49.53745937],
       [21.99547675],
       [60.46580273],
       [15.905424  ],
       [26.2155525 ],
       [24.6338537 ]])

In [27]:
# Testing the error of the model

mse_2019 = mean_squared_error(y_test, predict_2019)
mse_2019
# mse = 1.12, pretty low, so pretty accurate

1.017754313996736

In [4]:
r2 = r2_score(y_test, predict_2019)
r2
# r2 = 0.99. Very close to 1, so pretty accurate

0.9943970953123386

### Using the linear regression model to predict the levels of each country in 2020-2023

In [33]:
# Training a linear regression model and looping through each country to predict levels for 2020-2023

years = df_mean.columns[2:11]
X = np.array(years).reshape(-1, 1)


countries = df_mean['Country'].unique()

for country in countries:
    y_country = df_mean.loc[df_mean['Country'] == country, years]
    y_country = np.array(y_country).reshape(-1,1)
    
    model.fit(X, y_country)
    
    df_mean.loc[df_mean['Country'] == country, '2020'] = round(model.predict(np.array([[2020]]))[0][0], 2)
    df_mean.loc[df_mean['Country'] == country, '2021'] = round(model.predict(np.array([[2021]]))[0][0], 2)
    df_mean.loc[df_mean['Country'] == country, '2022'] = round(model.predict(np.array([[2022]]))[0][0], 2)
    df_mean.loc[df_mean['Country'] == country, '2023'] = round(model.predict(np.array([[2023]]))[0][0], 2)

In [34]:
df_mean

,Country,Continent,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,Asia,68.97,66.94,68.26,72.18,68.06,67.20,64.00,61.78,70.25,62.49,65.13,64.73,64.33,63.94
1,Albania,Europe,21.95,23.00,21.70,19.77,19.13,18.98,18.15,19.01,19.76,16.28,17.30,16.82,16.35,15.87
2,Algeria,Africa,21.27,21.56,22.76,21.19,22.64,22.49,23.06,23.33,22.73,22.68,23.64,23.86,24.08,24.29
3,Andorra,Europe,11.43,11.66,10.80,10.15,9.35,9.94,9.06,9.31,9.21,8.52,8.14,7.81,7.49,7.16
4,Angola,Africa,24.20,24.67,24.01,24.53,24.12,25.03,26.08,25.44,25.85,27.16,26.24,26.46,26.69,26.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela (Bolivarian Republic of),America,20.67,20.71,19.87,21.00,19.84,20.12,19.65,18.71,17.06,16.21,17.56,17.20,16.84,16.47
191,Viet Nam,Asia,22.37,20.67,21.67,22.62,20.08,20.47,22.37,20.10,20.09,20.89,20.00,19.81,19.62,19.42
192,Yemen,Asia,38.83,41.03,42.49,41.02,38.27,41.06,39.91,41.32,41.62,41.61,41.31,41.42,41.54,41.65
193,Zambia,Africa,17.09,17.33,17.55,17.24,17.29,17.43,17.32,16.99,16.99,16.90,17.08,17.05,17.02,16.99
194,Zimbabwe,Africa,13.28,13.27,13.21,13.10,13.12,13.27,13.09,13.15,13.12,13.08,13.07,13.05,13.04,13.02

In [ ]:
### Creating a dataframe and csv of just predictions for 2020-2023

df_predict = df_mean.iloc[:, [0, 1] + list(range(12, 16))]
df_predict

df_predict.to_csv('predictions_pm25.csv', index=False)

### Predicting when each country will reach WHO's Air Quality Guidnance
in progress

In [32]:
# Assuming you have loaded your dataset into df_mean
from sklearn.linear_model import LinearRegression

# Extract the years as a list from the column headers (columns 2 to 11)
years = df_mean.columns[2:11]
X = np.array(years).reshape(-1, 1)

# Loop through each country
countries = df_mean['Country'].unique()

for country in countries:
    # Extract the PM2.5 values for the current country
    y_country = df_mean.loc[df_mean['Country'] == country, years]
    y_country = np.array(y_country).reshape(-1,1)
    
    # Train the model
    model.fit(X, y_country)
    
    # Create hypothetical data for 5.5 PM2.5 value
    y_hypothetical = np.array([[5.5]])
    
    # Predict the year
    predicted_year = round(model.predict(y_hypothetical)[0][0], 2)
    
    print(f"The predicted year for {country} to reach a PM2.5 value of 5.5 is {predicted_year}")

The predicted year for Afghanistan to reach a PM2.5 value of 5.5 is 866.23
The predicted year for Albania to reach a PM2.5 value of 5.5 is 978.22
The predicted year for Algeria to reach a PM2.5 value of 5.5 is -414.51
The predicted year for Andorra to reach a PM2.5 value of 5.5 is 666.88
The predicted year for Angola to reach a PM2.5 value of 5.5 is -428.71
The predicted year for Antigua and Barbuda to reach a PM2.5 value of 5.5 is -312.17
The predicted year for Argentina to reach a PM2.5 value of 5.5 is 12.76
The predicted year for Armenia to reach a PM2.5 value of 5.5 is 1893.19
The predicted year for Australia to reach a PM2.5 value of 5.5 is 448.85
The predicted year for Austria to reach a PM2.5 value of 5.5 is 919.58
The predicted year for Azerbaijan to reach a PM2.5 value of 5.5 is 1472.31
The predicted year for Bahamas to reach a PM2.5 value of 5.5 is -195.53
The predicted year for Bahrain to reach a PM2.5 value of 5.5 is 216.39
The predicted year for Bangladesh to reach a PM2.5 value of 5.5 is 543.34
The predicted year for Barbados to reach a PM2.5 value of 5.5 is -429.95
The predicted year for Belarus to reach a PM2.5 value of 5.5 is 1123.77
The predicted year for Belgium to reach a PM2.5 value of 5.5 is 1126.23
The predicted year for Belize to reach a PM2.5 value of 5.5 is -368.67
The predicted year for Benin to reach a PM2.5 value of 5.5 is -416.01
The predicted year for Bhutan to reach a PM2.5 value of 5.5 is 610.79
The predicted year for Bolivia (Plurinational State of) to reach a PM2.5 value of 5.5 is 639.46
The predicted year for Bosnia and Herzegovina to reach a PM2.5 value of 5.5 is 1255.06
The predicted year for Botswana to reach a PM2.5 value of 5.5 is 248.78
The predicted year for Brazil to reach a PM2.5 value of 5.5 is 658.41
The predicted year for Brunei Darussalam to reach a PM2.5 value of 5.5 is 355.24
The predicted year for Bulgaria to reach a PM2.5 value of 5.5 is 1085.33
The predicted year for Burkina Faso to reach a PM2.5 value of 5.5 is -554.79
The predicted year for Burundi to reach a PM2.5 value of 5.5 is 5.65
The predicted year for Cabo Verde to reach a PM2.5 value of 5.5 is -611.17
The predicted year for Cambodia to reach a PM2.5 value of 5.5 is 287.72
The predicted year for Cameroon to reach a PM2.5 value of 5.5 is -1456.55
The predicted year for Canada to reach a PM2.5 value of 5.5 is 296.84
The predicted year for Central African Republic to reach a PM2.5 value of 5.5 is -126.89
The predicted year for Chad to reach a PM2.5 value of 5.5 is -530.03
The predicted year for Chile to reach a PM2.5 value of 5.5 is -18.98
The predicted year for China to reach a PM2.5 value of 5.5 is 2274.82
The predicted year for Colombia to reach a PM2.5 value of 5.5 is 618.17
The predicted year for Comoros to reach a PM2.5 value of 5.5 is -133.46
The predicted year for Congo to reach a PM2.5 value of 5.5 is 367.69
The predicted year for Cook Islands to reach a PM2.5 value of 5.5 is -75.86
The predicted year for Costa Rica to reach a PM2.5 value of 5.5 is 672.44
The predicted year for CÃ´te d'Ivoire to reach a PM2.5 value of 5.5 is -659.1
The predicted year for Croatia to reach a PM2.5 value of 5.5 is 829.16
The predicted year for Cuba to reach a PM2.5 value of 5.5 is -395.24
The predicted year for Cyprus to reach a PM2.5 value of 5.5 is 940.37
The predicted year for Czechia to reach a PM2.5 value of 5.5 is 933.52
The predicted year for Democratic People's Republic of Korea to reach a PM2.5 value of 5.5 is 2229.87
The predicted year for Democratic Republic of the Congo to reach a PM2.5 value of 5.5 is 51.65
The predicted year for Denmark to reach a PM2.5 value of 5.5 is 733.68
The predicted year for Djibouti to reach a PM2.5 value of 5.5 is 94.92
The predicted year for Dominica to reach a PM2.5 value of 5.5 is -346.1
The predicted year for Dominican Republic to reach a PM2.5 value of 5.5 is -244.38
The predicted year for Ecuador to reach a PM2.5 value of 5.5 is 341.05
The predicted year for Egypt to reach a PM2.5 value of 5.5 is -482.26
The predicted year for El Salvador to reach a PM2.5 value of 5.5 is 919.07
The predicted year for Equatorial Guinea to reach a PM2.5 value of 5.5 is -624.15
The predicted year for Eritrea to reach a PM2.5 value of 5.5 is -114.75
The predicted year for Estonia to reach a PM2.5 value of 5.5 is 528.38
The predicted year for Eswatini to reach a PM2.5 value of 5.5 is 24.21
The predicted year for Ethiopia to reach a PM2.5 value of 5.5 is 34.22
The predicted year for Fiji to reach a PM2.5 value of 5.5 is -104.21
The predicted year for Finland to reach a PM2.5 value of 5.5 is 448.94
The predicted year for France to reach a PM2.5 value of 5.5 is 950.22
The predicted year for Gabon to reach a PM2.5 value of 5.5 is -259.18
The predicted year for Gambia to reach a PM2.5 value of 5.5 is -671.01
The predicted year for Georgia to reach a PM2.5 value of 5.5 is 1079.21
The predicted year for Germany to reach a PM2.5 value of 5.5 is 990.22
The predicted year for Ghana to reach a PM2.5 value of 5.5 is -1142.24
The predicted year for Greece to reach a PM2.5 value of 5.5 is 1189.23
The predicted year for Grenada to reach a PM2.5 value of 5.5 is -432.41
The predicted year for Guatemala to reach a PM2.5 value of 5.5 is 1062.66
The predicted year for Guinea to reach a PM2.5 value of 5.5 is -455.9
The predicted year for Guinea-Bissau to reach a PM2.5 value of 5.5 is -550.2
The predicted year for Guyana to reach a PM2.5 value of 5.5 is -432.45
The predicted year for Haiti to reach a PM2.5 value of 5.5 is -312.49
The predicted year for Honduras to reach a PM2.5 value of 5.5 is 745.06
The predicted year for Hungary to reach a PM2.5 value of 5.5 is 821.87
The predicted year for Iceland to reach a PM2.5 value of 5.5 is 376.92
The predicted year for India to reach a PM2.5 value of 5.5 is 663.27
The predicted year for Indonesia to reach a PM2.5 value of 5.5 is 393.22
The predicted year for Iran (Islamic Republic of) to reach a PM2.5 value of 5.5 is -352.99
The predicted year for Iraq to reach a PM2.5 value of 5.5 is -87.19
The predicted year for Ireland to reach a PM2.5 value of 5.5 is 566.1
The predicted year for Israel to reach a PM2.5 value of 5.5 is 1141.95
The predicted year for Italy to reach a PM2.5 value of 5.5 is 1275.97
The predicted year for Jamaica to reach a PM2.5 value of 5.5 is -534.84
The predicted year for Japan to reach a PM2.5 value of 5.5 is 676.3
The predicted year for Jordan to reach a PM2.5 value of 5.5 is -229.77
The predicted year for Kazakhstan to reach a PM2.5 value of 5.5 is 1188.27
The predicted year for Kenya to reach a PM2.5 value of 5.5 is -29.03
The predicted year for Kiribati to reach a PM2.5 value of 5.5 is -1.49
The predicted year for Kuwait to reach a PM2.5 value of 5.5 is 160.65
The predicted year for Kyrgyzstan to reach a PM2.5 value of 5.5 is 1972.28
The predicted year for Lao People's Democratic Republic to reach a PM2.5 value of 5.5 is 475.09
The predicted year for Latvia to reach a PM2.5 value of 5.5 is 1065.81
The predicted year for Lebanon to reach a PM2.5 value of 5.5 is -2.84
The predicted year for Lesotho to reach a PM2.5 value of 5.5 is 112.52
The predicted year for Liberia to reach a PM2.5 value of 5.5 is -765.09
The predicted year for Libya to reach a PM2.5 value of 5.5 is 109.35
The predicted year for Lithuania to reach a PM2.5 value of 5.5 is 834.39
The predicted year for Luxembourg to reach a PM2.5 value of 5.5 is 773.05
The predicted year for Madagascar to reach a PM2.5 value of 5.5 is 112.73
The predicted year for Malawi to reach a PM2.5 value of 5.5 is 94.37
The predicted year for Malaysia to reach a PM2.5 value of 5.5 is 395.27
The predicted year for Maldives to reach a PM2.5 value of 5.5 is 144.07
The predicted year for Mali to reach a PM2.5 value of 5.5 is -443.18
The predicted year for Malta to reach a PM2.5 value of 5.5 is 945.02
The predicted year for Marshall Islands to reach a PM2.5 value of 5.5 is 10.16
The predicted year for Mauritania to reach a PM2.5 value of 5.5 is -785.09
The predicted year for Mauritius to reach a PM2.5 value of 5.5 is 36.7
The predicted year for Mexico to reach a PM2.5 value of 5.5 is 900.03
The predicted year for Micronesia (Federated States of) to reach a PM2.5 value of 5.5 is -48.68
The predicted year for Monaco to reach a PM2.5 value of 5.5 is 678.79
The predicted year for Mongolia to reach a PM2.5 value of 5.5 is 1160.45
The predicted year for Montenegro to reach a PM2.5 value of 5.5 is 1236.22
The predicted year for Morocco to reach a PM2.5 value of 5.5 is -145.97
The predicted year for Mozambique to reach a PM2.5 value of 5.5 is 19.21
The predicted year for Myanmar to reach a PM2.5 value of 5.5 is 598.94
The predicted year for Namibia to reach a PM2.5 value of 5.5 is 49.12
The predicted year for Nauru to reach a PM2.5 value of 5.5 is 16.11
The predicted year for Nepal to reach a PM2.5 value of 5.5 is 475.83
The predicted year for Netherlands to reach a PM2.5 value of 5.5 is 1040.38
The predicted year for New Zealand to reach a PM2.5 value of 5.5 is 472.6
The predicted year for Nicaragua to reach a PM2.5 value of 5.5 is 689.31
The predicted year for Niger to reach a PM2.5 value of 5.5 is -745.93
The predicted year for Nigeria to reach a PM2.5 value of 5.5 is -1135.55
The predicted year for Niue to reach a PM2.5 value of 5.5 is -87.87
The predicted year for Norway to reach a PM2.5 value of 5.5 is 486.04
The predicted year for occupied Palestinian territory, including east Jerusalem to reach a PM2.5 value of 5.5 is -299.55
The predicted year for Oman to reach a PM2.5 value of 5.5 is -21.65
The predicted year for Pakistan to reach a PM2.5 value of 5.5 is 661.94
The predicted year for Palau to reach a PM2.5 value of 5.5 is -49.24
The predicted year for Panama to reach a PM2.5 value of 5.5 is 433.98
The predicted year for Papua New Guinea to reach a PM2.5 value of 5.5 is -127.63
The predicted year for Paraguay to reach a PM2.5 value of 5.5 is 715.82
The predicted year for Peru to reach a PM2.5 value of 5.5 is 244.84
The predicted year for Philippines to reach a PM2.5 value of 5.5 is 417.35
The predicted year for Poland to reach a PM2.5 value of 5.5 is 1277.31
The predicted year for Portugal to reach a PM2.5 value of 5.5 is 621.71
The predicted year for Qatar to reach a PM2.5 value of 5.5 is 369.7
The predicted year for Republic of Korea to reach a PM2.5 value of 5.5 is 1162.61
The predicted year for Republic of Moldova to reach a PM2.5 value of 5.5 is 1064.16
The predicted year for North Macedonia to reach a PM2.5 value of 5.5 is 1783.22
The predicted year for Romania to reach a PM2.5 value of 5.5 is 842.81
The predicted year for Russian Federation to reach a PM2.5 value of 5.5 is 715.62
The predicted year for Rwanda to reach a PM2.5 value of 5.5 is 5.73
The predicted year for Saint Kitts and Nevis to reach a PM2.5 value of 5.5 is -303.08
The predicted year for Saint Lucia to reach a PM2.5 value of 5.5 is -391.26
The predicted year for Saint Vincent and the Grenadines to reach a PM2.5 value of 5.5 is -404.54
The predicted year for Samoa to reach a PM2.5 value of 5.5 is -69.05
The predicted year for San Marino to reach a PM2.5 value of 5.5 is 727.63
The predicted year for Sao Tome and Principe to reach a PM2.5 value of 5.5 is -492.12
The predicted year for Saudi Arabia to reach a PM2.5 value of 5.5 is -216.17
The predicted year for Senegal to reach a PM2.5 value of 5.5 is -585.59
The predicted year for Serbia to reach a PM2.5 value of 5.5 is 1350.02
The predicted year for Seychelles to reach a PM2.5 value of 5.5 is 286.31
The predicted year for Sierra Leone to reach a PM2.5 value of 5.5 is -809.06
The predicted year for Singapore to reach a PM2.5 value of 5.5 is 747.75
The predicted year for Slovakia to reach a PM2.5 value of 5.5 is 956.77
The predicted year for Slovenia to reach a PM2.5 value of 5.5 is 771.41
The predicted year for Solomon Islands to reach a PM2.5 value of 5.5 is -139.32
The predicted year for Somalia to reach a PM2.5 value of 5.5 is 13.72
The predicted year for South Africa to reach a PM2.5 value of 5.5 is -200.27
The predicted year for South Sudan to reach a PM2.5 value of 5.5 is -104.45
The predicted year for Spain to reach a PM2.5 value of 5.5 is 777.42
The predicted year for Sri Lanka to reach a PM2.5 value of 5.5 is 319.87
The predicted year for Sudan to reach a PM2.5 value of 5.5 is 19.23
The predicted year for Suriname to reach a PM2.5 value of 5.5 is -512.67
The predicted year for Sweden to reach a PM2.5 value of 5.5 is 458.17
The predicted year for Switzerland to reach a PM2.5 value of 5.5 is 827.58
The predicted year for Syrian Arab Republic to reach a PM2.5 value of 5.5 is 5.27
The predicted year for Tajikistan to reach a PM2.5 value of 5.5 is 2673.63
The predicted year for Thailand to reach a PM2.5 value of 5.5 is 479.5
The predicted year for Timor-Leste to reach a PM2.5 value of 5.5 is 199.23
The predicted year for Togo to reach a PM2.5 value of 5.5 is -575.33
The predicted year for Tonga to reach a PM2.5 value of 5.5 is -95.87
The predicted year for Trinidad and Tobago to reach a PM2.5 value of 5.5 is -402.06
The predicted year for Tunisia to reach a PM2.5 value of 5.5 is -263.85
The predicted year for TÃ¼rkiye to reach a PM2.5 value of 5.5 is 141.54
The predicted year for Turkmenistan to reach a PM2.5 value of 5.5 is 1342.4
The predicted year for Tuvalu to reach a PM2.5 value of 5.5 is -0.52
The predicted year for Uganda to reach a PM2.5 value of 5.5 is 2.53
The predicted year for Ukraine to reach a PM2.5 value of 5.5 is 1053.7
The predicted year for United Arab Emirates to reach a PM2.5 value of 5.5 is 179.43
The predicted year for United Kingdom of Great Britain and Northern Ireland to reach a PM2.5 value of 5.5 is 915.26
The predicted year for United Republic of Tanzania to reach a PM2.5 value of 5.5 is 22.79
The predicted year for United States of America to reach a PM2.5 value of 5.5 is 421.64
The predicted year for Uruguay to reach a PM2.5 value of 5.5 is -3.68
The predicted year for Uzbekistan to reach a PM2.5 value of 5.5 is 2097.49
The predicted year for Vanuatu to reach a PM2.5 value of 5.5 is -168.99
The predicted year for Venezuela (Bolivarian Republic of) to reach a PM2.5 value of 5.5 is 748.15
The predicted year for Viet Nam to reach a PM2.5 value of 5.5 is 408.8
The predicted year for Yemen to reach a PM2.5 value of 5.5 is -190.7
The predicted year for Zambia to reach a PM2.5 value of 5.5 is 73.82
The predicted year for Zimbabwe to reach a PM2.5 value of 5.5 is 49.0